/**
 * exportPalette.js
 * Exports the extracted color palette as a beautiful 1200×630 PNG image,
 * and provides clipboard copy utilities for CSS variables, JSON, and Tailwind.
 *
 * @module exportPalette
 */

// ============================================================
// PUBLIC API
// ============================================================

function ensureRoundRect(ctx) {
  if (!ctx.roundRect) {
    ctx.roundRect = function (x, y, w, h, r) {
      if (typeof r === 'number') r = { tl: r, tr: r, br: r, bl: r };
      ctx.beginPath();
      ctx.moveTo(x + r.tl, y);
      ctx.lineTo(x + w - r.tr, y);
      ctx.quadraticCurveTo(x + w, y, x + w, y + r.tr);
      ctx.lineTo(x + w, y + h - r.br);
      ctx.quadraticCurveTo(x + w, y + h, x + w, y + h - r.br);
      ctx.lineTo(x + r.bl, y + h);
      ctx.quadraticCurveTo(x, y + h, x, y + h - r.bl);
      ctx.lineTo(x, y + r.tl);
      ctx.quadraticCurveTo(x, y, x + r.tl, y);
      ctx.closePath();
    };
  }
}

function canvasToBlob(canvas, type = 'image/png', quality = 0.95) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      reject(new Error('canvas.toBlob timed out'));
    }, 10000);

    canvas.toBlob((blob) => {
      clearTimeout(timer);
      if (blob) {
        resolve(blob);
      } else {
        reject(new Error('canvas.toBlob returned null'));
      }
    }, type, quality);
  });
}

/**
 * Export palette as a 1200×630 PNG with the Coloris brand header,
 * gradient color bars, hex labels, and footer attribution.
 */
export async function exportPalettePNG(colors, options = {}) {
  if (!colors || colors.length === 0) return;

  const {
    width = 1200,
    height = 630,
    includeLogo = true,
    includeFooter = true,
    filename = generateFilename(),
  } = options;

  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext('2d');
  if (!ctx) return null;

  ensureRoundRect(ctx);
  drawBackground(ctx, width, height);
  if (includeLogo) drawHeader(ctx, width, colors);

  const colorBarArea = {
    x: 100,
    y: includeLogo ? 200 : 120,
    barWidth: (width - 260) / Math.min(colors.length, 6),
    barHeight: 180,
    gap: 12,
  };

  drawColorBars(ctx, colors, colorBarArea);
  drawHexLabels(ctx, colors, colorBarArea);

  if (includeFooter) drawFooter(ctx, width, height);

  try {
    const blob = await canvasToBlob(canvas, 'image/png', 0.95);
    if (blob) {
      downloadBlob(blob, filename);
      return blob;
    }
    return null;
  } catch {
    return null;
  }
}

export async function exportPaletteSVG(colors) {
  if (!colors || colors.length === 0) return null;

  const width = 1200;
  const height = 630;
  const barCount = Math.min(colors.length, 6);
  const barAreaLeft = 100;
  const barAreaRight = width - 100;
  const barTotalWidth = barAreaRight - barAreaLeft;
  const barWidth = (barTotalWidth - (barCount - 1) * 12) / barCount;
  const barY = 200;
  const barHeight = 180;

  const colorRects = colors.slice(0, barCount).map((c, i) => {
    const x = barAreaLeft + i * (barWidth + 12);
    return `<rect x="${x}" y="${barY}" width="${barWidth}" height="${barHeight}" rx="6" fill="${c.hex}"/>`;
  }).join('\n    ');

  const hexLabels = colors.slice(0, barCount).map((c, i) => {
    const x = barAreaLeft + i * (barWidth + 12) + barWidth / 2;
    return `<text x="${x}" y="${barY + barHeight + 36}" text-anchor="middle" font-family="JetBrains Mono, monospace" font-size="16" fill="#7A6B5D">${c.hex}</text>`;
  }).join('\n    ');

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">
  <rect width="${width}" height="${height}" fill="#F9F7F5"/>
  <rect x="0" y="0" width="${width}" height="${height}" fill="url(#bgGrad)"/>
  <defs>
    <linearGradient id="bgGrad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#F9F7F5" stop-opacity="1"/>
      <stop offset="100%" stop-color="#F1EDE8" stop-opacity="1"/>
    </linearGradient>
  </defs>
  <text x="100" y="100" font-family="Poppins, sans-serif" font-size="42" font-weight="900" fill="#5D4432" letter-spacing="-2">COLORIS</text>
  <text x="100" y="130" font-family="Poppins, sans-serif" font-size="16" font-weight="300" fill="#A6988A" letter-spacing="6">COLOR PALETTE</text>
  <line x1="100" y1="150" x2="160" y2="150" stroke="#C4A882" stroke-width="2"/>
  ${colorRects}
  ${hexLabels}
  <text x="${width - 100}" y="${height - 30}" text-anchor="end" font-family="Poppins, sans-serif" font-size="11" font-weight="300" fill="#A6988A">generated by coloris.app</text>
</svg>`;

  const blob = new Blob([svg], { type: 'image/svg+xml' });
  downloadBlob(blob, generateFilename('.svg'));
  return blob;
}

export async function copyAsCSS(colors) {
  if (!colors || colors.length === 0) return false;

  const lines = colors.map((c, i) => `  --color-${i + 1}: ${c.hex};`);
  const css = `:root {\n${lines.join('\n')}\n}`;

  return copyToClipboard(css, 'CSS variables copied to clipboard');
}

export async function copyAsJSON(colors) {
  if (!colors || colors.length === 0) return false;

  const json = JSON.stringify({
    palette: colors.map(c => ({
      hex: c.hex,
      rgb: { r: c.r, g: c.g, b: c.b },
      percentage: c.pct,
    })),
    generated: new Date().toISOString(),
    app: 'Coloris',
  }, null, 2);

  return copyToClipboard(json, 'JSON palette copied to clipboard');
}

export async function copyAsTailwind(colors) {
  if (!colors || colors.length === 0) return false;

  const entries = colors.map((c, i) => `    'coloris-${i + 1}': '${c.hex}'`);
  const config = `// Coloris palette — Tailwind CSS v3 extension\nmodule.exports = {\n  theme: {\n    extend: {\n      colors: {\n${entries.join(',\n')}\n      }\n    }\n  }\n};`;

  return copyToClipboard(config, 'Tailwind config copied to clipboard');
}

// ============================================================
// CANVAS RENDERING
// ============================================================

function drawBackground(ctx, width, height) {
  const gradient = ctx.createRadialGradient(width * 0.3, height * 0.3, 0, width * 0.5, height * 0.5, width * 0.8);
  gradient.addColorStop(0, '#F9F7F5');
  gradient.addColorStop(1, '#F1EDE8');
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, width, height);
}

function drawHeader(ctx, width, colors) {
  ctx.font = '900 42px Poppins, sans-serif';
  ctx.fillStyle = '#5D4432';
  ctx.textBaseline = 'top';
  ctx.textAlign = 'left';
  ctx.fillText('COLORIS', 100, 52);

  ctx.font = '300 14px Poppins, sans-serif';
  ctx.fillStyle = '#A6988A';

  const subtitle = 'COLOR PALETTE';
  let xPos = 100;
  for (let i = 0; i < subtitle.length; i++) {
    ctx.fillText(subtitle[i], xPos, 100);
    xPos += ctx.measureText(subtitle[i]).width + 6;
  }

  ctx.beginPath();
  ctx.moveTo(100, 130);
  ctx.lineTo(160, 130);
  ctx.strokeStyle = '#C4A882';
  ctx.lineWidth = 2;
  ctx.stroke();
}

function drawColorBars(ctx, colors, area) {
  const count = Math.min(colors.length, 6);

  colors.slice(0, count).forEach((color, i) => {
    const x = area.x + i * (area.barWidth + area.gap);
    const y = area.y;

    ctx.fillStyle = color.hex;

    ctx.beginPath();
    ctx.roundRect(x, y, area.barWidth, area.barHeight, 6);
    ctx.fill();

    const lighter = lightenColor(color.hex, 40);
    ctx.fillStyle = lighter;
    ctx.globalAlpha = 0.15;
    ctx.beginPath();
    ctx.roundRect(x, y, area.barWidth, 6, { topLeft: 6, topRight: 6 });
    ctx.fill();
    ctx.globalAlpha = 1;

    const darker = darkenColor(color.hex, 30);
    ctx.fillStyle = darker;
    ctx.globalAlpha = 0.08;
    ctx.beginPath();
    ctx.roundRect(x, y, area.barWidth, area.barHeight, 6);
    ctx.fill();
    ctx.globalAlpha = 1;
  });
}

function drawHexLabels(ctx, colors, area) {
  const count = Math.min(colors.length, 6);

  ctx.textAlign = 'center';
  ctx.textBaseline = 'top';
  ctx.font = '15px "JetBrains Mono", monospace';
  ctx.fillStyle = '#7A6B5D';

  colors.slice(0, count).forEach((color, i) => {
    const x = area.x + i * (area.barWidth + area.gap) + area.barWidth / 2;
    const y = area.y + area.barHeight + 16;
    ctx.fillText(color.hex, x, y);
  });
}

function drawFooter(ctx, width, height) {
  ctx.textAlign = 'right';
  ctx.textBaseline = 'bottom';
  ctx.font = '11px Poppins, sans-serif';
  ctx.fillStyle = '#A6988A';
  ctx.fillText('generated by coloris.app', width - 100, height - 30);
}

// ============================================================
// COLOR UTILITIES
// ============================================================

function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16),
  } : { r: 0, g: 0, b: 0 };
}

function rgbToHex(r, g, b) {
  const toHex = (c) => Math.max(0, Math.min(255, Math.round(c))).toString(16).padStart(2, '0');
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`.toUpperCase();
}

function lightenColor(hex, amount) {
  const { r, g, b } = hexToRgb(hex);
  return rgbToHex(
    Math.min(255, r + amount),
    Math.min(255, g + amount),
    Math.min(255, b + amount)
  );
}

function darkenColor(hex, amount) {
  const { r, g, b } = hexToRgb(hex);
  return rgbToHex(
    Math.max(0, r - amount),
    Math.max(0, g - amount),
    Math.max(0, b - amount)
  );
}

// ============================================================
// DOWNLOAD & CLIPBOARD HELPERS
// ============================================================

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function generateFilename(ext = '.png') {
  const date = new Date().toISOString().slice(0, 19).replace(/[:-]/g, '');
  return `coloris-palette-${date}${ext}`;
}

async function copyToClipboard(text, successMessage) {
  try {
    await navigator.clipboard.writeText(text);
    document.dispatchEvent(new CustomEvent('toast:show', {
      detail: { message: successMessage || 'Copied to clipboard', type: 'success' },
      bubbles: true,
    }));
    return true;
  } catch {
    try {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      document.dispatchEvent(new CustomEvent('toast:show', {
        detail: { message: successMessage || 'Copied to clipboard', type: 'success' },
        bubbles: true,
      }));
      return true;
    } catch {
      document.dispatchEvent(new CustomEvent('toast:show', {
        detail: { message: 'Failed to copy to clipboard', type: 'error' },
        bubbles: true,
      }));
      return false;
    }
  }
}
